name: Deploy to GitHub page via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js of at least 10.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install dependency and start angular-cli-ghpages's Deploy action
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npm install
        npm run ng -- deploy --no-silent --base-href=/Profolio/ --name="CyberExplosion" --email="minhkhoi632000@gmail.com" --message="What could possibly go wrong?"


# name: Deploy to GitHub Pages via angular-cli-ghpages
# 
# on: [push]
# 
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
# 
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
# 
#     - name: Use Node.js 10.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
# 
#     - name: Prepare and deploy
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         npm install
#         npm run ng -- deploy --base-href=/Profolio/ --name="CyberExplosion" --email="minhkhoi632000@gmail.com" --no-silent